name: dumper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  http: ^0.13.4
  flare_flutter: ^3.0.2
  carousel_pro: ^1.0.0
#  url_launcher: ^6.0.18
  shared_preferences: ^2.0.12
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  badges: ^2.0.2
  intl: ^0.17.0
  firebase_storage: ^11.0.6
  firebase_core_platform_interface: ^4.5.2
  firebase_auth: ^4.1.3
  google_sign_in: ^5.4.2
  twitter_login: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/